version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=enem
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/bitnami/postgresql
